In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
df=pd.read_csv('Mental_Health_Care_in_the_Last_4_Weeks.csv')

In [7]:
df

,Indicator,Group,State,Subgroup,Phase,Time Period,Time Period Label,Time Period Start Date,Time Period End Date,Value,LowCI,HighCI,Confidence Interval,Quartile Range,Suppression Flag
0,Took Prescription Medication for Mental Health...,National Estimate,United States,United States,2,13,"Aug 19 - Aug 31, 2020",08/19/2020,08/31/2020,19.4,19.0,19.8,19.0 - 19.8,NaN,NaN
1,Took Prescription Medication for Mental Health...,By Age,United States,18 - 29 years,2,13,"Aug 19 - Aug 31, 2020",08/19/2020,08/31/2020,18.7,17.2,20.3,17.2 - 20.3,NaN,NaN
2,Took Prescription Medication for Mental Health...,By Age,United States,30 - 39 years,2,13,"Aug 19 - Aug 31, 2020",08/19/2020,08/31/2020,18.3,17.3,19.2,17.3 - 19.2,NaN,NaN
3,Took Prescription Medication for Mental Health...,By Age,United States,40 - 49 years,2,13,"Aug 19 - Aug 31, 2020",08/19/2020,08/31/2020,20.4,19.5,21.3,19.5 - 21.3,NaN,NaN
4,Took Prescription Medication for Mental Health...,By Age,United States,50 - 59 years,2,13,"Aug 19 - Aug 31, 2020",08/19/2020,08/31/2020,21.2,20.2,22.2,20.2 - 22.2,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10399,Needed Counseling or Therapy But Did Not Get I...,By State,Virginia,Virginia,3.4,45,"Apr 27 - May 9, 2022",04/27/2022,05/09/2022,10.1,7.1,13.8,7.1 - 13.8,9.6-11.3,NaN
10400,Needed Counseling or Therapy But Did Not Get I...,By State,Washington,Washington,3.4,45,"Apr 27 - May 9, 2022",04/27/2022,05/09/2022,14.8,12.5,17.4,12.5 - 17.4,13.0-20.8,NaN
10401,Needed Counseling or Therapy But Did Not Get I...,By State,West Virginia,West Virginia,3.4,45,"Apr 27 - May 9, 2022",04/27/2022,05/09/2022,9.8,6.6,13.8,6.6 - 13.8,9.6-11.3,NaN
10402,Needed Counseling or Therapy But Did Not Get I...,By State,Wisconsin,Wisconsin,3.4,45,"Apr 27 - May 9, 2022",04/27/2022,05/09/2022,11.6,8.5,15.3,8.5 - 15.3,11.4-12.9,NaN
10403,Needed Counseling or Therapy But Did Not Get I...,By State,Wyoming,Wyoming,3.4,45,"Apr 27 - May 9, 2022",04/27/2022,05/09/2022,11.5,8.6,15.1,8.6 - 15.1,11.4-12.9,NaN

In [8]:
df.shape

(10404, 15)

In [9]:
df.info

<bound method DataFrame.info of                                                Indicator              Group  \
0      Took Prescription Medication for Mental Health...  National Estimate
1      Took Prescription Medication for Mental Health...             By Age
2      Took Prescription Medication for Mental Health...             By Age
3      Took Prescription Medication for Mental Health...             By Age
4      Took Prescription Medication for Mental Health...             By Age
...                                                  ...                ...
10399  Needed Counseling or Therapy But Did Not Get I...           By State
10400  Needed Counseling or Therapy But Did Not Get I...           By State
10401  Needed Counseling or Therapy But Did Not Get I...           By State
10402  Needed Counseling or Therapy But Did Not Get I...           By State
10403  Needed Counseling or Therapy But Did Not Get I...           By State

               State       Subgroup Phase  Time Period      Time Period Label  \
0      United States  United States     2           13  Aug 19 - Aug 31, 2020
1      United States  18 - 29 years     2           13  Aug 19 - Aug 31, 2020
2      United States  30 - 39 years     2           13  Aug 19 - Aug 31, 2020
3      United States  40 - 49 years     2           13  Aug 19 - Aug 31, 2020
4      United States  50 - 59 years     2           13  Aug 19 - Aug 31, 2020
...              ...            ...   ...          ...                    ...
10399       Virginia       Virginia   3.4           45   Apr 27 - May 9, 2022
10400     Washington     Washington   3.4           45   Apr 27 - May 9, 2022
10401  West Virginia  West Virginia   3.4           45   Apr 27 - May 9, 2022
10402      Wisconsin      Wisconsin   3.4           45   Apr 27 - May 9, 2022
10403        Wyoming        Wyoming   3.4           45   Apr 27 - May 9, 2022

      Time Period Start Date Time Period End Date  Value  LowCI  HighCI  \
0                 08/19/2020           08/31/2020   19.4   19.0    19.8
1                 08/19/2020           08/31/2020   18.7   17.2    20.3
2                 08/19/2020           08/31/2020   18.3   17.3    19.2
3                 08/19/2020           08/31/2020   20.4   19.5    21.3
4                 08/19/2020           08/31/2020   21.2   20.2    22.2
...                      ...                  ...    ...    ...     ...
10399             04/27/2022           05/09/2022   10.1    7.1    13.8
10400             04/27/2022           05/09/2022   14.8   12.5    17.4
10401             04/27/2022           05/09/2022    9.8    6.6    13.8
10402             04/27/2022           05/09/2022   11.6    8.5    15.3
10403             04/27/2022           05/09/2022   11.5    8.6    15.1

      Confidence Interval Quartile Range  Suppression Flag
0             19.0 - 19.8            NaN               NaN
1             17.2 - 20.3            NaN               NaN
2             17.3 - 19.2            NaN               NaN
3             19.5 - 21.3            NaN               NaN
4             20.2 - 22.2            NaN               NaN
...                   ...            ...               ...
10399          7.1 - 13.8       9.6-11.3               NaN
10400         12.5 - 17.4      13.0-20.8               NaN
10401          6.6 - 13.8       9.6-11.3               NaN
10402          8.5 - 15.3      11.4-12.9               NaN
10403          8.6 - 15.1      11.4-12.9               NaN

[10404 rows x 15 columns]>

In [40]:
df.isnull().sum()/df.shape[0]*100

Indicator                 0.0
Group                     0.0
State                     0.0
Subgroup                  0.0
Phase                     0.0
Time Period               0.0
Time Period Label         0.0
Time Period Start Date    0.0
Time Period End Date      0.0
Value                     0.0
LowCI                     0.0
HighCI                    0.0
Confidence Interval       0.0
Quartile Range            0.0
Suppression Flag          0.0
dtype: float64

In [41]:
df.duplicated().sum()

np.int64(0)

In [42]:
for i in df.select_dtypes(include="object").columns:
    print(df[i].value_counts())
    print("***"*10)

Indicator
Took Prescription Medication for Mental Health, Last 4 Weeks                                          2601
Received Counseling or Therapy, Last 4 Weeks                                                          2601
Took Prescription Medication for Mental Health And/Or Received Counseling or Therapy, Last 4 Weeks    2601
Needed Counseling or Therapy But Did Not Get It, Last 4 Weeks                                         2601
Name: count, dtype: int64
******************************
Group
By State                                         6732
By Age                                           1064
By Race/Hispanic ethnicity                        760
By Education                                      608
By Sex                                            304
By Presence of Symptoms of Anxiety/Depression     304
By Disability status                              168
By Gender identity                                156
By Sexual orientation                             156
National Estimate                                 152
Name: count, dtype: int64
******************************
State
United States           3672
Alabama                  132
Alaska                   132
Arizona                  132
Arkansas                 132
California               132
Colorado                 132
Connecticut              132
Delaware                 132
District of Columbia     132
Florida                  132
Georgia                  132
Hawaii                   132
Idaho                    132
Illinois                 132
Indiana                  132
Iowa                     132
Kansas                   132
Kentucky                 132
Louisiana                132
Maine                    132
Maryland                 132
Massachusetts            132
Michigan                 132
Minnesota                132
Mississippi              132
Missouri                 132
Montana                  132
Nebraska                 132
Nevada                   132
New Hampshire            132
New Jersey               132
New Mexico               132
New York                 132
North Carolina           132
North Dakota             132
Ohio                     132
Oklahoma                 132
Oregon                   132
Pennsylvania             132
Rhode Island             132
South Carolina           132
South Dakota             132
Tennessee                132
Texas                    132
Utah                     132
Vermont                  132
Virginia                 132
Washington               132
West Virginia            132
Wisconsin                132
Wyoming                  132
Name: count, dtype: int64
******************************
Subgroup
United States        152
18 - 29 years        152
30 - 39 years        152
40 - 49 years        152
50 - 59 years        152
                    ...
Cis-gender female     52
Transgender           52
Gay or lesbian        52
Straight              52
Bisexual              52
Name: count, Length: 80, dtype: int64
******************************
Phase
3.2                    1920
3.1                    1776
3 (Jan 6 â€“ Mar 29)     1728
2                      1440
3 (Oct 28 â€“ Dec 21)    1152
3.3                     960
3.4                     960
-1                      468
Name: count, dtype: int64
******************************
Time Period Label
Jan 26 - Feb 7, 2022           320
Mar 2 - Mar 14, 2022           320
Sep 15 - Sep 27, 2021          320
Sep 29 - Oct 11, 2021          320
Dec 29, 2021 - Jan 10, 2022    320
Dec 1 - Dec 13, 2021           320
Aug 18 - Aug 30, 2021          320
Sep 1 - Sep 13, 2021           320
Jul 21 - Aug 2, 2021           320
Aug 4 - Aug 16, 2021           320
Mar 30 - Apr 11, 2022          320
Apr 27 - May 9, 2022           320
Apr 28 - May 10, 2021          296
May 12 - May 24, 2021          296
Jun 23 - Jul 5, 2021           296
Apr 14 - Apr 26, 2021          296
May 26 - Jun 7, 2021           296
Jun 9 - Jun 21, 2021           296
Sep 2 - Sep 14, 2020           288
Aug 19 - Aug 31, 2020          288
Sep 30 - Oct 12, 2020          288
Sep 16 - Sep 28, 2020          288
Oct 28 - Nov 9, 2020           288
Oct 14 - Oct 26, 2020          288
Mar 3 - Mar 15, 2021           288
Dec 9 - Dec 21, 2020           288
Nov 25 - Dec 7, 2020           288
Jan 20 - Feb 1, 2021           288
Feb 17 - Mar 1, 2021           288
Jan 6 - Jan 18, 2021           288
Feb 3 - Feb 15, 2021           288
Mar 17 - Mar 29, 2021          288
Nov 11 - Nov 23, 2020          288
Feb 23 - Mar 1, 2022           116
Jul 6 - Jul 20, 2021            92
Oct 12 - Nov 30, 2021           92
Mar 30 - Apr 13, 2021           84
Dec 22, 2020 - Jan 5, 2021      84
Name: count, dtype: int64
******************************
Confidence Interval
17.450736      490
9.1 - 13.6       8
6.7 - 10.7       7
7.2 - 12.0       7
8.6 - 15.0       7
              ...
11.4 - 13.9      1
5.7 - 15.5       1
8.9 - 15.4       1
13.8 - 22.8      1
7.7 - 10.5       1
Name: count, Length: 7710, dtype: int64
******************************
Quartile Range
17.450736                 3672
9.8-11.2                    40
4.8-8.6                     28
9.6-11.2                    28
10.4-12.4                   27
                          ...
11.7-17.9                   10
28.5-33.6                   10
Estimate not reliable.       9
11.7-17.2                    9
13.0-20.4                    9
Name: count, Length: 501, dtype: int64
******************************

In [28]:
df.describe()

        Time Period        Value        LowCI       HighCI
count  10404.000000  9914.000000  9914.000000  9914.000000
mean      28.134948    17.450736    14.771565    20.475661
std       11.040210     8.270565     7.659396     9.052521
min        1.000000     1.400000     0.800000     2.000000
25%       20.000000    10.300000     8.000000    12.900000
50%       29.000000    16.200000    13.900000    19.200000
75%       37.000000    24.000000    20.800000    27.400000
max       45.000000    62.900000    53.200000    71.900000

In [13]:
df.fillna(df.Value.mean(),inplace=True)

In [14]:
df

,Indicator,Group,State,Subgroup,Phase,Time Period,Time Period Label,Time Period Start Date,Time Period End Date,Value,LowCI,HighCI,Confidence Interval,Quartile Range,Suppression Flag
0,Took Prescription Medication for Mental Health...,National Estimate,United States,United States,2,13,"Aug 19 - Aug 31, 2020",08/19/2020,08/31/2020,19.4,19.0,19.8,19.0 - 19.8,17.450736,17.450736
1,Took Prescription Medication for Mental Health...,By Age,United States,18 - 29 years,2,13,"Aug 19 - Aug 31, 2020",08/19/2020,08/31/2020,18.7,17.2,20.3,17.2 - 20.3,17.450736,17.450736
2,Took Prescription Medication for Mental Health...,By Age,United States,30 - 39 years,2,13,"Aug 19 - Aug 31, 2020",08/19/2020,08/31/2020,18.3,17.3,19.2,17.3 - 19.2,17.450736,17.450736
3,Took Prescription Medication for Mental Health...,By Age,United States,40 - 49 years,2,13,"Aug 19 - Aug 31, 2020",08/19/2020,08/31/2020,20.4,19.5,21.3,19.5 - 21.3,17.450736,17.450736
4,Took Prescription Medication for Mental Health...,By Age,United States,50 - 59 years,2,13,"Aug 19 - Aug 31, 2020",08/19/2020,08/31/2020,21.2,20.2,22.2,20.2 - 22.2,17.450736,17.450736
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10399,Needed Counseling or Therapy But Did Not Get I...,By State,Virginia,Virginia,3.4,45,"Apr 27 - May 9, 2022",04/27/2022,05/09/2022,10.1,7.1,13.8,7.1 - 13.8,9.6-11.3,17.450736
10400,Needed Counseling or Therapy But Did Not Get I...,By State,Washington,Washington,3.4,45,"Apr 27 - May 9, 2022",04/27/2022,05/09/2022,14.8,12.5,17.4,12.5 - 17.4,13.0-20.8,17.450736
10401,Needed Counseling or Therapy But Did Not Get I...,By State,West Virginia,West Virginia,3.4,45,"Apr 27 - May 9, 2022",04/27/2022,05/09/2022,9.8,6.6,13.8,6.6 - 13.8,9.6-11.3,17.450736
10402,Needed Counseling or Therapy But Did Not Get I...,By State,Wisconsin,Wisconsin,3.4,45,"Apr 27 - May 9, 2022",04/27/2022,05/09/2022,11.6,8.5,15.3,8.5 - 15.3,11.4-12.9,17.450736
10403,Needed Counseling or Therapy But Did Not Get I...,By State,Wyoming,Wyoming,3.4,45,"Apr 27 - May 9, 2022",04/27/2022,05/09/2022,11.5,8.6,15.1,8.6 - 15.1,11.4-12.9,17.450736

In [15]:
df.fillna(df.LowCI.mean(),inplace=True)

In [16]:
df.fillna(df.HighCI.mean(),inplace=True)

In [27]:
df.dtypes

Indicator                  object
Group                      object
State                      object
Subgroup                   object
Phase                      object
Time Period                 int64
Time Period Label          object
Time Period Start Date     object
Time Period End Date       object
Value                     float64
LowCI                     float64
HighCI                    float64
Confidence Interval        object
Quartile Range             object
Suppression Flag          float64
dtype: object

In [31]:
df['Time Period Start Date'] = pd.to_datetime(df['Time Period Start Date'])

In [32]:
df['Time Period End Date'] = pd.to_datetime(df['Time Period End Date'])

In [37]:
df.dtypes

Indicator                         object
Group                             object
State                             object
Subgroup                          object
Phase                             object
Time Period                        int64
Time Period Label                 object
Time Period Start Date    datetime64[ns]
Time Period End Date      datetime64[ns]
Value                            float64
LowCI                            float64
HighCI                           float64
Confidence Interval               object
Quartile Range                    object
Suppression Flag                 float64
dtype: object